# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/getEnv.ipynb (unless otherwise specified).

__all__ = ['SEARCHENDPOINT', 'BRANCH', 'CONFIGURL', 'DAXENDPOINT']

# Cell
from nicHelper.secrets import getSecret

# Cell
import os
# GITHUBTOKEN = os.environ.get('GITHUBTOKEN', '')
try:
    GITHUBTOKEN = getSecret(name = 'githubToken', region = 'ap-southeast-1')['githubToken']
except:
    GITHUBTOKEN = None
SEARCHENDPOINT = os.environ.get('SEARCHENDPOINT')
BRANCH = os.environ.get('BRANCH')
CONFIGURL = f'https://raw.githubusercontent.com/thanakijwanavit/villaConfig/{BRANCH}/search/cloudsearch.yaml'
DAXENDPOINT = os.environ.get('DAXENDPOINT')

# Cell
if GITHUBTOKEN:
    print(f'github token is {"".join("*" for _ in GITHUBTOKEN)}')