# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/openai/openAiSearchCache.ipynb (unless otherwise specified).

__all__ = ['CacheTable']

# Cell
import os
os.environ['MPLCONFIGDIR'] = '/tmp/matplotlib'
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute
import pandas as pd
from getEnv import DAXENDPOINT, BRANCH

# Cell
class CacheTable(Model):
    class Meta:
        table_name = f"openai-search-cache-experiment"
        region = "ap-southeast-1"
        dax_read_endpoints = [DAXENDPOINT] if DAXENDPOINT else None
        dax_write_endpoints = [DAXENDPOINT] if DAXENDPOINT else None
    key = UnicodeAttribute(hash_key=True)
    search_result = UnicodeAttribute()
