version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chatWithDavinci"
s3_bucket = "chat-with-davinci"
s3_prefix = "chatWithDavinci"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
