AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    chat function to be able to interact with openai
    
Globals:
  Function:
    Timeout: 10
    CodeUri: ./app
    Runtime: python3.8
    Layers:
      - !Ref LambdaLayer
    Environment:
      Variables:
        REGION: !Ref REGION
        BRANCH: !Ref BRANCH
      
      
Parameters: 
  BRANCH: 
    Type: String
    Default: dev-manual
    Description: root branch name
  REGION:
    Type: String
    Default: 'ap-southeast-1'
    
    
    
Resources:
  ######## api gateway #######
  Endpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        
  ######## functions ######
  Chat:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ['-',[ "chat",!Ref BRANCH ]]
      Handler: app.chat
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /chat
            Method: get
            RestApiId: !Ref Endpoint
            
###### lambdaLayer ######

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambdalayer
      ContentUri: ./layer/package.zip
      CompatibleRuntimes:
        - python3.8

  LayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaLayer
      Principal: "*"



Outputs:
  ApiId:
    Value: !Ref Endpoint
  Endpoint:
    Value: !Sub 'https://${Endpoint}.execute-api.${REGION}.amazonaws.com/Prod/'
