# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ParseInputError": "chat.ipynb",
         "parseEvent": "chat.ipynb",
         "talkWithOpenAI": "chat.ipynb",
         "EventInput": "chat.ipynb",
         "chat": "chat.ipynb",
         "GITHUBTOKEN": "getEnv.ipynb",
         "SEARCHENDPOINT": "getEnv.ipynb",
         "BRANCH": "getEnv.ipynb",
         "CONFIGURL": "getEnv.ipynb",
         "DAXENDPOINT": "getEnv.ipynb",
         "recordSearch": "recordSearch.ipynb",
         "QueryInput": "searchKevin.ipynb",
         "Item": "searchKevin.ipynb",
         "InputClass": "return_dataclass.ipynb",
         "Field": "searchKevin.ipynb",
         "Result": "searchKevin.ipynb",
         "Hits": "searchKevin.ipynb",
         "SearchResponse": "searchKevin.ipynb",
         "Body": "searchKevin.ipynb",
         "Output": "searchKevin.ipynb",
         "logSearch": "search.ipynb",
         "logValidation": "search.ipynb",
         "logTransform": "search.ipynb",
         "logConfig": "search.ipynb",
         "logParseResult": "search.ipynb",
         "ResponseParsingError": "search.ipynb",
         "QueryParsingError": "search.ipynb",
         "ConfigLoadingError": "search.ipynb",
         "SearchError": "search.ipynb",
         "search": "search.ipynb",
         "cache": "search.ipynb",
         "lambdaSearch": "search.ipynb",
         "SearchResultRecord": "searchCounter.ipynb",
         "SearchTermRecord": "searchCounter.ipynb",
         "SearchResultMonthlyRecordTable": "searchCounter.ipynb",
         "SearchResultDailyRecordTable": "searchCounter.ipynb",
         "SearchTermDailyRecordTable": "searchCounter.ipynb",
         "Input": "searchKevin.ipynb",
         "Search": "searchKevin.ipynb",
         "searchKevin": "searchKevin.ipynb"}

modules = ["chat.py",
           "getEnv.py",
           "recordSearch.py",
           "return_dataclass.py",
           "search.py",
           "searchCounter.py",
           "searchKevin.py"]

doc_url = "https://thanakijwanavit.github.io/src/"

git_url = "https://github.com/thanakijwanavit/src/tree/main/"

def custom_doc_links(name): return None
