# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/chat.ipynb (unless otherwise specified).

__all__ = ['ParseInputError', 'parseEvent', 'talkWithOpenAI', 'EventInput', 'chat']

# Cell
import os, openai, requests
from awsSchema.apigateway import Event, Response
from copy import deepcopy
from beartype import beartype
from nicHelper.secrets import getSecret
from openai import Completion

# Cell
class ParseInputError(Exception):
    pass

# Cell
EventInput = dict

@beartype
def parseEvent(event):
    eventCopy = deepcopy(event)
    body = Event.parseBody(eventCopy)

    try:
        inputText = body['inputText']
    except KeyError:
        raise ParseInputError('inputText is not in body')

    return inputText

@beartype
def talkWithOpenAI(inputText: str)->str:
    openai.api_key = getSecret('openai')['key']
    r = Completion.create(engine="davinci", prompt=inputText, max_tokens=100, temperature=0.2)
    print("r: ", r)

    return r["choices"][0]["text"]

# Cell
def chat(event, *args):
    try:
        inputText = parseEvent(event)
        response = talkWithOpenAI(inputText)
        return Response.returnSuccess(body = response)
    except Exception as e:
        return Response.returnError(message=str(e))