# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/recordSearch.ipynb (unless otherwise specified).

__all__ = ['recordSearch']

# Cell
from .searchCounter import SearchResultRecord, SearchTermRecord
from .searchKevin import Search


# Cell

def recordSearch(event, *context):
    try:
        searchTerm = event.get('searchTerm', None)
        if searchTerm is None:
            print("no search term provided")
            raise Exception("no search term provided")
        print("search term: " + searchTerm)
        cprcodes = event.get('cprcodes', None)
        if cprcodes is None:
            print("no cprcodes provided")
            raise Exception("no cprcodes provided")
        SearchResultRecord.recordResult(searchTerm=searchTerm, cprcodes=cprcodes)
        SearchTermRecord.recordResult(searchTerm=searchTerm, cprcodes=cprcodes)
        print("successfully saved search result")[searchTerm]
    except Exception as e:
        print("error: " + str(e))
